---
  
    - name: Creating an empty
      shell: |
        #dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
        #dnf distro-sync
        sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        #yum update -y




    
