---
- name: Add Workers to the Swarm
  become: true
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars['swarm-manager']['worker_token']['stdout'] }}"
    remote_addrs: [ "{{ hostvars['swarm-manager']['ansible_default_ipv4']['address'] }}:2377" ]
  tags: swarm
